from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal


ExitSide = Literal["YES", "NO"]
ExitAction = Literal["SELL_YES", "SELL_NO", "NO_ACTION"]


class ExitReason(str, Enum):
    KILL_SWITCH_TRIGGERED = "KILL_SWITCH_TRIGGERED"
    RESIDUAL_INVENTORY_DETECTED = "RESIDUAL_INVENTORY_DETECTED"
    EDGE_DISAPPEARED = "EDGE_DISAPPEARED"
    MAX_DRAWDOWN_REACHED = "MAX_DRAWDOWN_REACHED"
    MARKET_EXPIRED_OR_NEAR_EXPIRY = "MARKET_EXPIRED_OR_NEAR_EXPIRY"
    MANUAL_DRY_RUN = "MANUAL_DRY_RUN"


@dataclass(frozen=True)
class ExitDryRunContract:
    """
    Contract generated by the exit planner in dry-run mode.

    This object must never submit, cancel, or modify real orders.
    It only describes what the system would do if live execution were enabled.
    """

    contract_id: str
    generated_at: datetime
    dry_run: bool
    allow_real_execution: bool

    market_id: str
    condition_id: str | None
    token_id: str | None

    side: ExitSide
    action: ExitAction
    reason: ExitReason

    current_position_size: float
    planned_exit_size: float

    reference_price: float | None
    max_slippage_bps: int
    estimated_fees: float
    estimated_slippage: float

    risk_approved: bool
    kill_switch_active: bool

    notes: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def validate_safety(self) -> None:
        if self.dry_run is not True:
            raise ValueError("ExitDryRunContract must always be dry_run=True.")

        if self.allow_real_execution is not False:
            raise ValueError("ExitDryRunContract cannot allow real execution.")

        if self.planned_exit_size < 0:
            raise ValueError("planned_exit_size cannot be negative.")

        if self.current_position_size < 0:
            raise ValueError("current_position_size cannot be negative.")

        if self.planned_exit_size > self.current_position_size:
            raise ValueError("planned_exit_size cannot exceed current_position_size.")

        if self.max_slippage_bps < 0:
            raise ValueError("max_slippage_bps cannot be negative.")

    def to_dict(self) -> dict[str, Any]:
        self.validate_safety()

        return {
            "contract_id": self.contract_id,
            "generated_at": self.generated_at.isoformat(),
            "dry_run": self.dry_run,
            "allow_real_execution": self.allow_real_execution,
            "market_id": self.market_id,
            "condition_id": self.condition_id,
            "token_id": self.token_id,
            "side": self.side,
            "action": self.action,
            "reason": self.reason.value,
            "current_position_size": self.current_position_size,
            "planned_exit_size": self.planned_exit_size,
            "reference_price": self.reference_price,
            "max_slippage_bps": self.max_slippage_bps,
            "estimated_fees": self.estimated_fees,
            "estimated_slippage": self.estimated_slippage,
            "risk_approved": self.risk_approved,
            "kill_switch_active": self.kill_switch_active,
            "notes": self.notes,
            "metadata": self.metadata,
        }


def build_exit_dry_run_contract(
    *,
    contract_id: str,
    market_id: str,
    side: ExitSide,
    reason: ExitReason,
    current_position_size: float,
    planned_exit_size: float,
    condition_id: str | None = None,
    token_id: str | None = None,
    reference_price: float | None = None,
    max_slippage_bps: int = 50,
    estimated_fees: float = 0.0,
    estimated_slippage: float = 0.0,
    risk_approved: bool = False,
    kill_switch_active: bool = False,
    notes: list[str] | None = None,
    metadata: dict[str, Any] | None = None,
) -> ExitDryRunContract:
    action: ExitAction

    if planned_exit_size <= 0:
        action = "NO_ACTION"
    elif side == "YES":
        action = "SELL_YES"
    else:
        action = "SELL_NO"

    contract = ExitDryRunContract(
        contract_id=contract_id,
        generated_at=datetime.now(timezone.utc),
        dry_run=True,
        allow_real_execution=False,
        market_id=market_id,
        condition_id=condition_id,
        token_id=token_id,
        side=side,
        action=action,
        reason=reason,
        current_position_size=current_position_size,
        planned_exit_size=planned_exit_size,
        reference_price=reference_price,
        max_slippage_bps=max_slippage_bps,
        estimated_fees=estimated_fees,
        estimated_slippage=estimated_slippage,
        risk_approved=risk_approved,
        kill_switch_active=kill_switch_active,
        notes=notes or [],
        metadata=metadata or {},
    )

    contract.validate_safety()
    return contract